# Generated by Django 3.0.6 on 2020-05-13 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('status', models.CharField(blank=True, choices=[('App', 'Applied'), ('OA1', 'Online Assessment 1'), ('OA2', 'Online Assessment 2'), ('OA3', 'Online Assessment 3'), ('Ph-I-1', 'Phone Interview 1'), ('Ph-I-2', 'Phone Interview 1'), ('Vid-I-1', 'Video Interview 1'), ('Vid-I-2', 'Video Interview 2'), ('Ons-I', 'Onsite Interview'), ('O', 'Offer'), ('R', 'Rejection'), ('A', 'Accepted Offer'), ('D', 'Declined Offer')], max_length=30)),
                ('date_applied', models.DateField(null=True)),
                ('date_online_assessment', models.DateField(null=True)),
                ('date_phone_interview', models.DateField(null=True)),
                ('date_video_interview', models.DateField(null=True)),
                ('date_onsite_interiew', models.DateField(null=True)),
                ('date_final', models.DateField(null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('notes_html', models.TextField(blank=True, default='', editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_applied'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
