# Generated by Django 3.0.6 on 2020-05-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
