# Generated by Django 3.0.6 on 2020-05-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200513_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date_final',
            new_name='date_final_decision',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('Applied', 'Applied'), ('Online Assessment 1', 'Online Assessment 1'), ('Online Assessment 2', 'Online Assessment 2'), ('Online Assessment 3', 'Online Assessment 3'), ('Phone Interview 1', 'Phone Interview 1'), ('Phone Interview 1', 'Phone Interview 1'), ('Video Interview 1', 'Video Interview 1'), ('Video Interview 2', 'Video Interview 2'), ('Onsite Interview', 'Onsite Interview'), ('Offer', 'Offer'), ('Rejection', 'Rejection'), ('Accepted Offer', 'Accepted Offer'), ('Declined Offer', 'Declined Offer')], max_length=30),
        ),
    ]
