# Generated by Django 3.0.6 on 2020-05-13 20:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200513_2022'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='job',
            managers=[
                ('online_jobs', django.db.models.manager.Manager()),
            ],
        ),
    ]
