# Generated by Django 3.0.6 on 2020-05-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20200513_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_rejected',
            field=models.DateField(null=True),
        ),
    ]
